package com.azcord.models;

public enum Permission {
    ADMINISTRATOR, MANAGE_CHANNELS, MANAGE_SERVER,
    MANAGE_ROLES, CREATE_INVITE, KICK_MEMBERS, 
    BAN_MEMBERS, DELETE_MESSAGES, MUTE_MEMBERS, SEND_MESSAGES, MANAGE_MESSAGES; 
}
